apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: zvj7yt4jw-python 
  janus-idp.io/tekton: zvj7yt4jw-python
  backstage.io/kubernetes-id: zvj7yt4jw-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zvj7yt4jw-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml