apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zvj7yt4jw-python
  janus-idp.io/tekton: zvj7yt4jw-python
  backstage.io/kubernetes-id: zvj7yt4jw-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zvj7yt4jw-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
