apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: zvj7yt4jw-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zvj7yt4jw-python 
  name: zvj7yt4jw-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: zvj7yt4jw-python 
